# Assignment 1
Based on numpy


In [6]:
import numpy as np

# Q1: Questions on Basic NumPy Array

## (a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [7]:
arr = np.array([1, 2, 3, 6, 4, 5])
arr
arr[::-1]

array([5, 4, 6, 3, 2, 1])

## (b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any twoNumPy in-built methods

In [8]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

print(array1)
f1 = array1.flatten(order='C')
f2 = array1.flatten(order='F')
print("\nC-Style/Row Major: ",f1)
print("Fortran-Style/Column Major: ", f2)

[[1 2 3]
 [2 4 5]
 [1 2 3]]

C-Style/Row Major:  [1 2 3 2 4 5 1 2 3]
Fortran-Style/Column Major:  [1 2 1 2 4 2 3 5 3]


## (c) Compare the following numpy arrays:arr1 = np.array([[1, 2], [3, 4]])arr2 = np.array([[1, 2], [3, 4]])

In [9]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print(np.array_equal(arr1, arr2))

True


## (d) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

#### 3 Ways to find most frequenct element 
1. np.bincount(arrName).argmax() <i> only supports +ve int, fastest </i>
2. uniques, counts = np.unique(arrName, return_counts=True)
3. from collections import Counter <br>
   counter = Counter(arrName) <br>
   counter.most_common(1)[0][0]

In [20]:
from collections import Counter
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

ctr1 = Counter(x)
ctr2 = Counter(y)

mostFreqInX = ctr1.most_common(1)[0][0]
mostFreqInXIndices = np.where(x==mostFreqInX)
print(mostFreqInX,"appears at,", mostFreqInXIndices)

mostFreqInY = np.bincount(y).argmax()
mostFreqInYIndices = np.where(y==mostFreqInY)
print(mostFreqInY,"appears at,", mostFreqInYIndices)

1 appears at, (array([0, 5, 7, 8, 9]),)
1 appears at, (array([0, 1, 2]),)


In [11]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')


## (e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), 
find <br> 
i. Sum of all elements<br>ii. Sum of all elements row-wise<br>iii. Sum of all elements column-wise

In [25]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

sumofElem   = np.sum(gfg)
sumRowwise = np.sum(gfg, axis=1) # 1 for row, 0 for col
sumColwise = np.sum(gfg, axis=0)
print("Sum of all elems",sumofElem)
print("Sum of all elems row-wise\n",sumRowwise)
print("Sum of all elems col-wise\n",sumColwise)


Sum of all elems 45
Sum of all elems row-wise
 [[14]
 [16]
 [15]]
Sum of all elems col-wise
 [[20  9 16]]


## (f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), 
find<br>i. Sum of diagonal elements<br>ii. Eigen values of matrix<br>iii. Eigen vectors of matrix<br>iv. Inverse of matrix<br>v. Determinant of matrix

np.linalg <i> provides linear algebra functions</i><br>
.inv(), .det(), .eig(), .solve(), .matrix_rank(), .svd(), .norm()

In [30]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

diagonalElem = np.diagonal(n_array)
print("Sum of diagonals, ", np.sum(diagonalElem))

eigenvalues, eigenvector = np.linalg.eig(n_array)
print("Eigen Values",eigenvalues)

print("\nEigen Vector", eigenvector)


Sum of diagonals,  176
Eigen Values [98.16835147 28.097044   49.73460452]

Eigen Vector [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


## (g) Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]] q = [[4, 5], [6, 7]] <br>
ii. p = [[1, 2], [2, 3], [4, 5]] q = [[4, 5, 1], [6, 7, 2]]

In [59]:
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
p = np.array(p)
q = np.array(q)
print(np.matmul(p,q))

covMat = np.cov(p,q)

[[16 19]
 [26 31]]


In [60]:
p = [[1, 2], [2, 3], [4, 5]] 
q = [[4, 5, 1], [6, 7, 2]]
p = np.array(p)
q  = np.array(q)

print(np.matmul(p,q))


q_trans = q.T
combined = np.vstack((p, q_trans))
covMat = np.cov(combined, rowvar = True)
print("\n Covariance of matrices")
print(covMat)

[[16 19  5]
 [26 31  8]
 [46 55 14]]

 Covariance of matrices
[[0.5 0.5 0.5 1.  1.  0.5]
 [0.5 0.5 0.5 1.  1.  0.5]
 [0.5 0.5 0.5 1.  1.  0.5]
 [1.  1.  1.  2.  2.  1. ]
 [1.  1.  1.  2.  2.  1. ]
 [0.5 0.5 0.5 1.  1.  0.5]]


## (h) For the matrices:  find inner, outer and cartesian product?
x = np.array([[2, 3, 4], [3, 2, 9]]); 
y = np.array([[1, 5, 0], [5, 10, 3]]),

In [63]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner = np.inner(x,y)
outer = np.outer(x,y)

#for cartesian product
from itertools import product
cartesian = np.array(list(product(x,y)))
print("Cartesian Product:\n", cartesian)

Cartesian Product:
 [[[ 2  3  4]
  [ 1  5  0]]

 [[ 2  3  4]
  [ 5 10  3]]

 [[ 3  2  9]
  [ 1  5  0]]

 [[ 3  2  9]
  [ 5 10  3]]]


# Q2: Based on NumPy Mathematics and Statistics

## (a) 
For the array: array = np.array([[1, -2, 3],[-4, 5, -6]]) <br>
i. Find element-wise absolute value<br>
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for eachrow.<br>
iii. Mean, Median and Standard Deviation of flattened array, of each column, andeach row

In [104]:
array = np.array([[1, -2, 3],[-4, 5, -6]])

print("Element-wise absolute values:\n ", np.abs(array))

flatArr = array.flatten()

flatttenPercentile = np.percentile(flatArr,[25,50,75])
rowPercentile = np.percentile(array,[25,50,75],axis=1)
colPercentile = np.percentile(array,[25,50,75],axis=0)


print("For flattened Array: ")
print("Percentiles ", flatttenPercentile)
print("Mean: ",np.mean(flatArr))
print("Median: ",np.median(flatArr))
print("Std: ",np.std(flatArr).round(3))

print("\n\nFor Each Row of Array: ")
print("Percentiles \n", rowPercentile)
print("Mean: ",np.mean(array,axis=1))
print("Median: ",np.median(array,axis=1))
print("Std: ",np.std(array,axis=1).round(3))

print("\n\nFor Each Col of Array: ")
print("Percentiles\n ", colPercentile)
print("Mean: ",np.mean(array,axis=0))
print("Median: ",np.median(array,axis=0))
print("Std: ",np.std(array,axis=0).round(3))

Element-wise absolute values:
  [[1 2 3]
 [4 5 6]]
For flattened Array: 
Percentiles  [-3.5 -0.5  2.5]
Mean:  -0.5
Median:  -0.5
Std:  3.862


For Each Row of Array: 
Percentiles 
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean:  [ 0.66666667 -1.66666667]
Median:  [ 1. -4.]
Std:  [2.055 4.784]


For Each Col of Array: 
Percentiles
  [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Mean:  [-1.5  1.5 -1.5]
Median:  [-1.5  1.5 -1.5]
Std:  [2.5 3.5 4.5]


## (b) Find floor, ceilingand truncated value, rounded values
For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]).

In [111]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print("Floor vals: ",np.floor(a))
print("Ceil vals: ",np.ceil(a))
print("Truncated vals: ",np.trunc(a))
print("Rounded Vals: ", np.round(a,0))

Floor vals:  [-2. -2. -1.  0.  1.  1.  3.]
Ceil vals:  [-1. -1. -0.  1.  2.  2.  3.]
Truncated vals:  [-1. -1. -0.  0.  1.  1.  3.]
Rounded Vals:  [-2. -2. -0.  0.  2.  2.  3.]


# Q3: Based on Searching and Sorting

## (a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), 
find<br>i. Sorted array<br>ii. Indices of sorted array<br>iii. 4 smallest elementsiv. 5 largest elements

In [118]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

print(np.sort(array))
print(np.argsort(array))
print(np.sort(array)[:4])
print(np.sort(array)[-5:][::-1])

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[453  62  54  52  16]


## (b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), 
find<br>i. Integer elements only<br>ii. Float elements only

In [119]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print("Integer elements: ",array[array==array.astype(int)])
print("Float elements: ",array[array!=array.astype(int)])

Integer elements:  [1. 2. 3. 2.]
Float elements:  [1.2 2.2]


# Q4 :

## (a) Write a function named img_to_array(path) that reads an image from a specified path and<br>save it as text file on local machine?<br> (Note: use separate cases for RGB and Grey Scaleimages)

In [1]:
import cv2 as cv

def img_to_array(path):
    img = cv.imread(path)

    if img is None:
        print("Error: Image not found or path is incorrect.")
        return
    if len(img.shape) ==2:
        #grayscale image
        output_file = "Grayscale_img.txt"
        np.savetxt(output_file,img,fmt="%d")
        print(f"Grayscale image is saved as {output_file}")
    elif len(img.shape)==3 and img.shape[2]==3:
        #RGB image
        output_file = "RGB_img.txt"
        r,g,b=cv.split(img) #splitting into channels
        with open(output_file,'w') as f:
            f.write("Red Channel: \n")
            np.savetxt(f,r,fmt="%d")
            f.write("\nGreen Channel:\n")
            np.savetxt(f,r,fmt="%d")
            f.write("\nBlue Channel:\n")
            np.savetxt(f,r,fmt="%d")
        print(f"RGB image is saved as {output_file}")
    else:
        print("Unsupported image format.")

img_to_array("https://machinelearningknowledge.ai/wp-content/uploads/2024/05/image2.jpg")

Error: Image not found or path is incorrect.


## (b) Load the saved file into jupyter notebook?

In [ ]:
def load_rgb_image_fromt_text(filepath):
    with open(filepath,'r') as f:
        lines = f.readlines()

    #split lines into rgb channels
    r_start = lines.index("Red Channel:\n")+1
    g_start = lines.index("Green Channel:\n")
    b_start = lines.index("Blue Channel: \n")

    r_lines = lines[r_start:g_start-1]
    g_lines = lines[g_start+1:b_start-1]
    b_lines = lines[b_start+1:]

    r = np.array([[int(val) for val in line.split()] for line in r_lines], dtype=np.uint8)
    g = np.array([[int(val) for val in line.split()] for line in g_lines], dtype=np.uint8)
    b = np.array([[int(val) for val in line.split()] for line in b_lines], dtype=np.uint8)

    #merge channels
    rgb_image = np.stack((r,g,b), axis=-1)
    return rgb_image

rgb_image = load_rgb_image_fromt_text("/content/rgb_image_data.txt")
import matplotlib.pyplot as plt
plt.imshow(cv.cvtColor(rgb_img, cv.COLOR_BGR2RGB))  # OpenCV loads in BGR
plt.title("RGB Image")
plt.axis('off')
plt.show()